### ISSUE TITLE
I think you should credit xrpgame in this repo

### ISSUE THREAD

**Issue by DenkingOfficial** [Gerschel/xyz-plot-grid#3]
I looked into your code and see a lot of similarities with this repo:

https://github.com/xrpgame/xyz_plot_script

If you use his code I think it will be good to credit the original creator

His code:

![image](https://user-images.githubusercontent.com/38957619/201437770-442c5580-7a58-49ef-b245-5e6f8c7e69d8.png)

Your code:

![image](https://user-images.githubusercontent.com/38957619/201437803-94901d77-f88c-47d4-b373-7a6086f69eb8.png)

It's the same

**Comment by Gerschel** [comment]
I absolutely did not use his code. I grabbed the original x/y, and modified it in the areas that pertain to it, draw_xy_grid(), Script.run(), draw_grid_annotations. So no, I'm merely extending the original of a1111 and plan to push an improved version of the orginial xy, to work faster and use less memory.

**Comment by Gerschel** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/scripts/xy_grid.py
![image](https://user-images.githubusercontent.com/9631031/201468445-cf9ccf5b-66a7-4d03-8f51-8ad17053dea5.png)

**Comment by Gerschel** [comment]
![Web capture_12-11-2022_2148_](https://user-images.githubusercontent.com/9631031/201469499-e3b469c3-6bd6-48ba-b3ff-ce1cdce34b49.jpeg)

**Comment by DenkingOfficial** [comment]
Now I understand
Sorry for bothering you 
Thank you so much for your explanation!!!
