### ISSUE TITLE
cannot import name 'get_correct_sampler' from 'modules.processing'

### ISSUE THREAD

**Issue by Harvester62** [Gerschel/xyz-plot-grid#4]
After the latest updates to SD Web UI (current installed version is hash [3596af0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3596af07493ab7981ef92074f979eeee8fa624c4)) the "Random grid.py" script doesn't load and returns the following error message in the console:

Error loading script: Random grid.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\scripts\Random grid.py", line 27, in <module>
    from modules.processing import process_images, Processed, get_correct_sampler, StableDiffusionProcessingTxt2Img
ImportError: cannot import name 'get_correct_sampler' from 'modules.processing' (C:\stable-diffusion-webui\modules\processing.py)

My command line arguments are as follows:
set COMMANDLINE_ARGS=--xformers --opt-split-attention --disable-safe-unpickle --api --deepdanbooru --allow-code --administrator --medvram

My system is Windows 10, 32GB RAM, GTX1070 8GB VRAM, Python 3.10.6, Nvidia Drivers 526.98, CUDA v12.0

Note: the same error happens with the script "Random grid.py"

**Comment by Gerschel** [comment]
Thank you for letting me know. I'm going to investigate.

**Comment by Gerschel** [comment]
There were some changes upstream, they removed  "get_correct_sampler" from "modules/processing.py", and replaced the retrieval of samplers names with a different script, "modules/sd_samplers.py".  

Currently it looks like this causes another bug upstream, where plotting samplers on x/y, does not take affect.  
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4860

I've pushed a fix to solve the first problem. Will investigate if I can solve the second issue in my code, but this has the potential to break if they fix the issue upstream, it may be better to wait and see if they fix the script in "modules/sd_samplers.py".  

I will leave this issue open, as I don't consider it completely fixed as of yet.

**Comment by Gerschel** [comment]
Situation seems resolved. Don't hesitate to tell me I'm wrong if I'm wrong. I'm going to close this as fixed. Thank you for making me aware.

**Comment by Gerschel** [comment]
The sampler name changes, when using sampler in plotting, but the actual sampler does not change. I'm going to dive in to see what is not getting passed to the actual process.

**Comment by Harvester62** [comment]
Great! Thank you for looking into this issue.

**Comment by Gerschel** [comment]
Samplers name resolved, case-sensitive
